### ISSUE TITLE
Add age penalty

### ISSUE THREAD

**Issue by fdietze** [social-protocols/news#20]
How much does cumulative attention correlate with age?

**Comment by johnwarden** [comment]
Good question. If we can map attention to age, based on the average age of a story that has accumulated a given amount of attention, then apply the same age penalty that HN applies for that amount of time. 

My guess is that this could result in a similar story "velocity" to what exists on HN -- that is, a similar distribution of the amount of time a story spends at each rank. I think velocity may be an important part of the dynamic of HN.
