### ISSUE TITLE
Make margins on mobile more similar to original HN

### ISSUE THREAD

**Issue by johnwarden** [social-protocols/news#43]
The larger margins in iphone result in fewer stories on the feont page.

**Comment by johnwarden** [comment]
![Uploading F73460AE-E7BE-4FDC-B747-834C237415B7.jpeg…]()

**Comment by johnwarden** [comment]
![Uploading DDF12EDB-B388-4E21-B89E-BF9A31090AD0.png…]()

https://user-images.githubusercontent.com/508886/193922205-ed0f6c41-98c8-4636-9acf-6268db68c42a.MOV

**Comment by fdietze** [comment]
Is it enough now?

**Comment by johnwarden** [comment]
The only place where I see excessive margin is next to the upvote link, which we will remove with issues #73
