### ISSUE TITLE
Out Of Storage strategy

### ISSUE THREAD

**Issue by fdietze** [social-protocols/news#54]
Since our database is growing indefinitely, we need a strategy to deal with limited storage.

At first, we could just delete old data from the database.
Later see how we can store the huge aggregated dataset.

**Comment by fdietze** [comment]
I just checked the size of the database file, `135M` at this time:
```sql
select (max(sampleTime)-min(sampleTime))/3600.0/24 from dataset;
2.38450231481482
```

It means that `135M` can hold about `2.38 days` of data. Our volume is `3G`, so it should be able to hold data from about `54 days` in total.

**Comment by johnwarden** [comment]
Deploying this commit crashed the site due to "out of storage" errors while seeding the database. Reverting.

https://social-protocols.zulipchat.com/#narrow/stream/373832-general/topic/news

**Comment by johnwarden** [comment]
The problem is that deleting requires some scratch disk space apparently. Maybe we can modify the SQL statement not to delete too much at once.

**Comment by johnwarden** [comment]
Okay this still doesn't solve the problem. We need to delete the data during the crawl, not on deployment.
