### ISSUE TITLE
Basic SEO Stuff (Essential)

### ISSUE THREAD

**Issue by johnwarden** [social-protocols/news#68]
Might as well try to capture a little SEO traffic.

- [x] Put "Hacker News" in title (e.g. "Quality News: Hacker News Rankings")
- [x] Put story title and "Hacker News" in title of /stats pages (e.g. "Hacker News Story Stats: What's New in Python 3.11")
- [x] Breadcrumbs. E.g. https://ourdomain > hacker news story stats > what's new in Python 3.11
- [ ] 301 redirect fly.io address to https://news.social-protocols.org/

**Comment by fdietze** [comment]
is this essential for posting it on HN?
