### ISSUE TITLE
Fix "database is locked" errors in production

### ISSUE THREAD

**Issue by johnwarden** [social-protocols/news#93]
We see this errors sometimes when a request happens while the crawl post-processing is running. HTTP requests that query the database will be blocked until the postprocessing is finished, and if it takes too long the queries will time out. In that case we see this error in the logs:

2022-11-22T02:14:20Z app[73fcccb4] ewr [info]time=2022-11-22T02:14:20.209Z level=ERROR msg="executing handler" url="/stats?id=33699917" err="database is locked"

**Comment by fdietze** [comment]
https://news.ycombinator.com/item?id=34247738
